### ISSUE TITLE
Fix markdownlint github action

### ISSUE THREAD

**Issue by lubronzhan** [vmware-tanzu/load-balancer-operator-for-kubernetes#181]
**Bug description**
it failed when running linting
https://github.com/vmware-tanzu/load-balancer-operator-for-kubernetes/actions/runs/8244213459/job/22546053852?pr=180
```
Run make lint-markdown
markdownlint -c md-config.json .
/opt/hostedtoolcache/node/14.21.3/x64/lib/node_modules/markdownlint-cli/node_modules/markdownlint/lib/md056.js:22
        expectedCount ||= actualCount;
                      ^^^

SyntaxError: Unexpected token '||='
    at wrapSafe (internal/modules/cjs/loader.js:1029:16)
    at Module._compile (internal/modules/cjs/loader.js:1078:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/opt/hostedtoolcache/node/14.21.3/x64/lib/node_modules/markdownlint-cli/node_modules/markdownlint/lib/rules.js:58:3)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
make: *** [Makefile:181: lint-markdown] Error 1
Error: Process completed with exit code 2.
0s
0s
0s

```

Maybe switching to v2 will fix it https://github.com/DavidAnson/markdownlint-cli2/blob/main/README.md
**Affected product area (please put an X in all that apply)**

- [ ] Docs
- [ ] Installation
- [ ] Plugin
- [ ] Security
- [x] Test and Release
- [ ] User Experience

**Expected behavior**
Test passed
**Steps to reproduce the bug**

**Version** (include the SHA if the version is not obvious)

**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, manifests, etc)**

**Comment by lubronzhan** [comment]
Completed
